select * from customer limit 20;

--Q1 What is the total revenue generated by male vs female customer
select gender, SUM(purchase_amount) as revenue
from customer
group by gender ;

--Q2 Which customer used a discount but still purchase more than the avg purchase amount
select customer_id , purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount >= (select avg(purchase_amount) from customer);

--Q3 Which are the 5 products with the highest avg review rating
select item_purchased , ROUND(avg(review_rating::numeric),2) as "Average Product Rating"
from customer 
group by item_purchased
order by avg(review_rating) desc
limit 5;

--Q4 Compare the avg purchased amount between standard and express shipping
select shipping_type , 
round(avg(purchase_amount),2)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type;

--Q5 Do subscribe customer spend more? compare avg spend and total revenue between subscribe and non subscribe
select subscription_status,
count(customer_id) as total_customer,
round(avg(purchase_amount),2) as avg_spend,
round(sum(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by  total_revenue , avg_spend desc ;

--Q6 Which 5 product have the highest percentage of purchase with discount applied
select item_purchased ,
round(100* sum(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/count(*),2) as discount_rate
from customer 
group by item_purchased
order by discount_rate desc
limit 5;

--Q7 Segnment customer into new, returning , loyal based on their total no. of purchase and 
--show the count of each segnment 
with customer_type as (
select customer_id , previous_purchases,
CASE WHEN previous_purchases = 1 Then 'New'
	 WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
	 ELSE 'Loyal'
	 END AS customer_segnment
	 from customer
	 )
	 select customer_segnment , count(*) as "number of customer"
	 from customer_type
	 group by customer_segnment;

--Q8 What are the top 3 most purchase product within each category
with item_counts as (
select category,
item_purchased,
COUNT(customer_id) as total_orders,
ROW_NUMBER() OVER(partition by category order by count(customer_id) DESC) as item_rank
from customer 
group by category , item_purchased
)
select item_rank , category, item_purchased, total_orders
from item_counts
where item_rank <= 3;

--Q9 Are the customer who are repeat buyers (more than 5 previous purchases) also likely to subscribe
select subscription_status,
COUNT(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status;

--Q10 What is the revenue contribution of each age group
select age_group,
sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue DESC;
	 